-- =====================================================================
-- Hridaya Creations — PostgreSQL schema (reference DDL)
-- Mirrors the JPA entity model. Hibernate can also generate this
-- automatically via JPA_DDL_AUTO; this script is for explicit/managed
-- schema deployments. Safe to run on an empty database.
-- =====================================================================

-- ----------------------------------------------------------------------
-- Roles & Users (RBAC)
-- ----------------------------------------------------------------------
CREATE TABLE roles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version     BIGINT,
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ,
    created_by  VARCHAR(150),
    updated_by  VARCHAR(150),
    name        VARCHAR(30)  NOT NULL,
    description VARCHAR(255),
    CONSTRAINT uk_role_name UNIQUE (name)
);

CREATE TABLE users (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version            BIGINT,
    created_at         TIMESTAMPTZ NOT NULL,
    updated_at         TIMESTAMPTZ,
    created_by         VARCHAR(150),
    updated_by         VARCHAR(150),
    first_name         VARCHAR(60)  NOT NULL,
    last_name          VARCHAR(60)  NOT NULL,
    email              VARCHAR(150) NOT NULL,
    mobile_number      VARCHAR(15)  NOT NULL,
    password           VARCHAR(255) NOT NULL,
    enabled            BOOLEAN      NOT NULL DEFAULT TRUE,
    account_non_locked BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_user_email  UNIQUE (email),
    CONSTRAINT uk_user_mobile UNIQUE (mobile_number)
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE
);

-- ----------------------------------------------------------------------
-- Catalog
-- ----------------------------------------------------------------------
CREATE TABLE categories (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version       BIGINT,
    created_at    TIMESTAMPTZ NOT NULL,
    updated_at    TIMESTAMPTZ,
    created_by    VARCHAR(150),
    updated_by    VARCHAR(150),
    category_name VARCHAR(120)  NOT NULL,
    description   VARCHAR(1000),
    image_url     VARCHAR(500),
    status        VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT uk_category_name UNIQUE (category_name)
);

CREATE TABLE products (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           BIGINT,
    created_at        TIMESTAMPTZ NOT NULL,
    updated_at        TIMESTAMPTZ,
    created_by        VARCHAR(150),
    updated_by        VARCHAR(150),
    name              VARCHAR(200)  NOT NULL,
    description       TEXT,
    short_description VARCHAR(500),
    category_id       BIGINT        NOT NULL,
    selling_price     NUMERIC(12,2) NOT NULL,
    original_price    NUMERIC(12,2),
    stock_quantity    INTEGER       NOT NULL DEFAULT 0,
    sku               VARCHAR(80)   NOT NULL,
    product_status    VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',
    featured          BOOLEAN       NOT NULL DEFAULT FALSE,
    customizable      BOOLEAN       NOT NULL DEFAULT FALSE,
    average_rating    NUMERIC(3,2)  DEFAULT 0,
    rating_count      INTEGER       NOT NULL DEFAULT 0,
    CONSTRAINT uk_product_sku   UNIQUE (sku),
    CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES categories (id)
);
CREATE INDEX idx_product_name     ON products (name);
CREATE INDEX idx_product_category ON products (category_id);
CREATE INDEX idx_product_status   ON products (product_status);

CREATE TABLE product_tags (
    product_id BIGINT      NOT NULL,
    tag        VARCHAR(60),
    CONSTRAINT fk_product_tags_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);

CREATE TABLE product_images (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version       BIGINT,
    created_at    TIMESTAMPTZ NOT NULL,
    updated_at    TIMESTAMPTZ,
    created_by    VARCHAR(150),
    updated_by    VARCHAR(150),
    product_id    BIGINT       NOT NULL,
    image_url     VARCHAR(500) NOT NULL,
    public_id     VARCHAR(255),
    primary_image BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT fk_product_image_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);

-- ----------------------------------------------------------------------
-- Cart
-- ----------------------------------------------------------------------
CREATE TABLE carts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version    BIGINT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ,
    created_by VARCHAR(150),
    updated_by VARCHAR(150),
    user_id    BIGINT NOT NULL,
    CONSTRAINT uk_cart_user UNIQUE (user_id),
    CONSTRAINT fk_cart_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE cart_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version    BIGINT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ,
    created_by VARCHAR(150),
    updated_by VARCHAR(150),
    cart_id    BIGINT        NOT NULL,
    product_id BIGINT        NOT NULL,
    quantity   INTEGER       NOT NULL,
    unit_price NUMERIC(12,2) NOT NULL,
    CONSTRAINT uk_cart_item UNIQUE (cart_id, product_id),
    CONSTRAINT fk_cart_item_cart    FOREIGN KEY (cart_id)    REFERENCES carts (id)    ON DELETE CASCADE,
    CONSTRAINT fk_cart_item_product FOREIGN KEY (product_id) REFERENCES products (id)
);

-- ----------------------------------------------------------------------
-- Addresses
-- ----------------------------------------------------------------------
CREATE TABLE addresses (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         BIGINT,
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ,
    created_by      VARCHAR(150),
    updated_by      VARCHAR(150),
    user_id         BIGINT       NOT NULL,
    full_name       VARCHAR(120) NOT NULL,
    mobile_number   VARCHAR(15)  NOT NULL,
    house_number    VARCHAR(100),
    street          VARCHAR(255) NOT NULL,
    city            VARCHAR(100) NOT NULL,
    state           VARCHAR(100) NOT NULL,
    country         VARCHAR(100) NOT NULL,
    pincode         VARCHAR(12)  NOT NULL,
    default_address BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_address_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX idx_address_user ON addresses (user_id);

-- ----------------------------------------------------------------------
-- Orders
-- ----------------------------------------------------------------------
CREATE TABLE orders (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version               BIGINT,
    created_at            TIMESTAMPTZ NOT NULL,
    updated_at            TIMESTAMPTZ,
    created_by            VARCHAR(150),
    updated_by            VARCHAR(150),
    order_number          VARCHAR(40)   NOT NULL,
    user_id               BIGINT        NOT NULL,
    status                VARCHAR(20)   NOT NULL DEFAULT 'PENDING',
    payment_status        VARCHAR(20)   NOT NULL DEFAULT 'PENDING',
    payment_method        VARCHAR(30)   NOT NULL DEFAULT 'CASH_ON_DELIVERY',
    subtotal              NUMERIC(12,2) NOT NULL,
    gst_amount            NUMERIC(12,2) NOT NULL,
    delivery_charge       NUMERIC(12,2) NOT NULL,
    total_amount          NUMERIC(12,2) NOT NULL,
    notes                 VARCHAR(1000),
    cancel_reason         VARCHAR(500),
    placed_at             TIMESTAMPTZ,
    delivered_at          TIMESTAMPTZ,
    shipping_full_name    VARCHAR(120) NOT NULL,
    shipping_mobile       VARCHAR(15)  NOT NULL,
    shipping_house_number VARCHAR(100),
    shipping_street       VARCHAR(255) NOT NULL,
    shipping_city         VARCHAR(100) NOT NULL,
    shipping_state        VARCHAR(100) NOT NULL,
    shipping_country      VARCHAR(100) NOT NULL,
    shipping_pincode      VARCHAR(12)  NOT NULL,
    CONSTRAINT uk_order_number UNIQUE (order_number),
    CONSTRAINT fk_order_user FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX idx_order_user   ON orders (user_id);
CREATE INDEX idx_order_status ON orders (status);

CREATE TABLE order_items (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      BIGINT,
    created_at   TIMESTAMPTZ NOT NULL,
    updated_at   TIMESTAMPTZ,
    created_by   VARCHAR(150),
    updated_by   VARCHAR(150),
    order_id     BIGINT        NOT NULL,
    product_id   BIGINT,
    product_name VARCHAR(200)  NOT NULL,
    sku          VARCHAR(80),
    unit_price   NUMERIC(12,2) NOT NULL,
    quantity     INTEGER       NOT NULL,
    line_total   NUMERIC(12,2) NOT NULL,
    image_url    VARCHAR(500),
    CONSTRAINT fk_order_item_order   FOREIGN KEY (order_id)   REFERENCES orders (id) ON DELETE CASCADE,
    CONSTRAINT fk_order_item_product FOREIGN KEY (product_id) REFERENCES products (id)
);

-- ----------------------------------------------------------------------
-- Wishlist & Reviews
-- ----------------------------------------------------------------------
CREATE TABLE wishlists (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version    BIGINT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ,
    created_by VARCHAR(150),
    updated_by VARCHAR(150),
    user_id    BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    CONSTRAINT uk_wishlist_user_product UNIQUE (user_id, product_id),
    CONSTRAINT fk_wishlist_user    FOREIGN KEY (user_id)    REFERENCES users (id)    ON DELETE CASCADE,
    CONSTRAINT fk_wishlist_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);

CREATE TABLE reviews (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version     BIGINT,
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ,
    created_by  VARCHAR(150),
    updated_by  VARCHAR(150),
    user_id     BIGINT  NOT NULL,
    product_id  BIGINT  NOT NULL,
    rating      INTEGER NOT NULL,
    review_text VARCHAR(2000),
    CONSTRAINT uk_review_user_product UNIQUE (user_id, product_id),
    CONSTRAINT fk_review_user    FOREIGN KEY (user_id)    REFERENCES users (id)    ON DELETE CASCADE,
    CONSTRAINT fk_review_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);

-- ----------------------------------------------------------------------
-- Security tokens & audit
-- ----------------------------------------------------------------------
CREATE TABLE refresh_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token       VARCHAR(512) NOT NULL,
    user_id     BIGINT       NOT NULL,
    expiry_date TIMESTAMPTZ  NOT NULL,
    revoked     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uk_refresh_token UNIQUE (token),
    CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE password_reset_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token       VARCHAR(255) NOT NULL,
    user_id     BIGINT       NOT NULL,
    expiry_date TIMESTAMPTZ  NOT NULL,
    used        BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uk_password_reset_token UNIQUE (token),
    CONSTRAINT fk_password_reset_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE audit_logs (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action       VARCHAR(40) NOT NULL,
    entity_type  VARCHAR(60),
    entity_id    VARCHAR(60),
    performed_by VARCHAR(150),
    details      VARCHAR(2000),
    ip_address   VARCHAR(60),
    created_at   TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_audit_action       ON audit_logs (action);
CREATE INDEX idx_audit_entity       ON audit_logs (entity_type, entity_id);
CREATE INDEX idx_audit_performed_by ON audit_logs (performed_by);
