spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com.hridayacreations: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

app:
  seed:
    sample-data-enabled: true
